const COMPONENT_HEIGHT = 40;
export const PIN_RADIUS = 10;
export const LIGHTBULB_RADIUS = COMPONENT_HEIGHT / 2;
export const INITIAL_WIRE_LENGTH = COMPONENT_HEIGHT;
export const COMPONENT_CONTAINER_HEIGHT = 120;
